### ISSUE TITLE
 配置好 也进入抢票 但当有票的时候会报错 

### ISSUE THREAD

**Issue by memoinry** [post-soldier/bupt-gym#1]
报错如下 不知道是不是需要配置node环境导致
![image](https://github.com/post-soldier/bupt-gym/assets/110704980/9e9f73fe-97fe-4883-b12b-1b5837f631a3)

**Comment by post-soldier** [comment]
羽毛球还是健身房？

**Comment by post-soldier** [comment]
我查了一下，应该是缺少node环境，装个nodejs就行

**Comment by post-soldier** [comment]
现在不需要nodejs环境了
