### ISSUE TITLE
过滑块验证后，程序未响应

### ISSUE THREAD

**Issue by BanChiGaBonBon** [post-soldier/bupt-gym#3]
你好，我预约羽毛球场过滑块验证后，程序卡住未响应，该如何解决呢？谢谢！

**Comment by post-soldier** [comment]
你是几点运行的？我设计的是在十一点快十二点时运行，一到12点自动抢。如果不在这个时间段运行的话就会卡住，不知道是不是这个问题，我待会会传一个没有时间限制的版本用于试验。

**Comment by post-soldier** [comment]
> 你好，我预约羽毛球场过滑块验证后，程序卡住未响应，该如何解决呢？谢谢！

你是几点运行的？我设计的是在十一点快十二点时运行，一到12点自动抢。如果不在这个时间段运行的话就会卡住，不知道是不是这个问题，我待会会传一个没有时间限制的版本用于试验。

**Comment by BanChiGaBonBon** [comment]
> > 你好，我预约羽毛球场过滑块验证后，程序卡住未响应，该如何解决呢？谢谢！
> 
> 你是几点运行的？我设计的是在十一点快十二点时运行，一到12点自动抢。如果不在这个时间段运行的话就会卡住，不知道是不是这个问题，我待会会传一个没有时间限制的版本用于试验。

就是刚刚两点多运行的，而且羽毛球场是上午十点开放预约，所以如果限制时间段的话可能需要改一下。

**Comment by post-soldier** [comment]
> > > 你好，我预约羽毛球场过滑块验证后，程序卡住未响应，该如何解决呢？谢谢！
> 
> > 
> 
> > 你是几点运行的？我设计的是在十一点快十二点时运行，一到12点自动抢。如果不在这个时间段运行的话就会卡住，不知道是不是这个问题，我待会会传一个没有时间限制的版本用于试验。
> 
> 
> 
> 就是刚刚两点多运行的，而且羽毛球场是上午十点开放预约，所以如果限制时间段的话可能需要改一下。

对的对的，是十点，我搞混了。程序写的是对的。

**Comment by post-soldier** [comment]
> 你好，我预约羽毛球场过滑块验证后，程序卡住未响应，该如何解决呢？谢谢！

我已经上传了对应的测试版本，你可以下载测试一下

**Comment by BanChiGaBonBon** [comment]
> > 你好，我预约羽毛球场过滑块验证后，程序卡住未响应，该如何解决呢？谢谢！
> 
> 我已经上传了对应的测试版本，你可以下载测试一下

成功了，非常感谢！
