### ISSUE TITLE
老哥带带，滑块验证的包怎么下载

### ISSUE THREAD

**Issue by Raiden-cn** [post-soldier/bupt-gym#6]
已经安装了requirements.txt里的依赖，但是还是会报找不到这个包，网上也没有相关信息。
import slider_verify.TecentSliderVerify
这个是你自己买的服务之类的吗？
我想在你基础上改成定时并且能自动获取PHPSESSID的

**Comment by Raiden-cn** [comment]
release版我是可以用的

**Comment by Raiden-cn** [comment]
还有个问题，时间比以前多了一截
之前的time_slots= {1: '08:00-09:00', 2: '09:00-10:00', 3: '10:00-11:00', 4: '11:00-12:00', 6: '12:00-13:00', 7: '13:00-14:00', 8: '14:00-15:00', 9: '15:00-16:00', 10: '16:00-17:00', 11: '17:00-18:00', 12: '18:00-19:00', 13: '19:00-20:00', 14: '20:00-21:00', 15: '21:00-22:00'}

现在多了一个12:00-12:45时段最新的时段对应是这样的
{1: '08:00-09:00', 2: '09:00-10:00', 3: '10:00-11:00', 4: '11:00-12:00', 5: '11:40-12:40', 6: '12:00-12:45',  7: '12:00-13:00', 8: '13:00-14:00', 9: '14:00-15:00', 10: '15:00-16:00', 11: '16:00-17:00', 12: '17:00-18:00', 13: '18:00-19:00', 14: '19:00-20:00', 15: '20:00-21:00', 16: '21:00-22:00'}

**Comment by post-soldier** [comment]
更新了
你下载最近的试试

**Comment by post-soldier** [comment]
这个是我自己写的，selenium模拟不是js逆向。
自动获取应该比较困难，因为他要微信认证，你可以抓包看看。

**Comment by Raiden-cn** [comment]
感谢回复，感谢开源
