### ISSUE TITLE
大佬，help help，please

### ISSUE THREAD

**Issue by XxxFpy** [post-soldier/bupt-gym#9]
关闭Reqable代理执行main执行窗口报错后马上就闪退了，也不会出现可视化预约界面
<img width="863" alt="d73178252d14286af999b0010ea5795" src="https://github.com/user-attachments/assets/6cc3c7a8-00f6-4ada-be27-24b0f8d6ae64">

**Comment by Raiden-cn** [comment]
把PHPSESSID放到上一级
